### ISSUE TITLE
Feature Request: "Other" option for non-listed schools.

### ISSUE THREAD

**Issue by HamletHat** [RunningMSN/CycleTrack#1]
Hello, thanks for this useful tool! I have applied to schools outside of the US (specifically Canada) and want to be able to include this data. However, the current upload process does not allow for any schools to be included that are not among the available list of schools on CycleTrack. I would like to be able to add and name schools to my graph. Thank you.

**Comment by RunningMSN** [comment]
Hi there, thanks for your suggestion! We are going to add all Canadian schools to CycleTrack. We'll give an update in this thread once it's been added!

**Comment by RunningMSN** [comment]
All Canadian schools are now available through the 'Add MD' menu. Thanks again!
