### ISSUE TITLE
Cycle Status Graphs

### ISSUE THREAD

**Issue by laurendaddi** [RunningMSN/CycleTrack#3]
Hi, I use CycleTrack and have some suggestions for new features. Not sure if this is the best place to relay them but here they are:

Mostly regarding the cycle status graphs, the data is pretty hard to read when there's only 1-2 observations. I suggest using a log scaling on the y-axis in the full form when everything is listed across the ~8 month period.

Then I also suggest including the option to zoom in/out, and to overlay/remove different types of data. For instance, the ability to toggle to only show acceptances, or only show secondary received dates.

Also I noticed that the 2022 data has been removed, I wonder if you can add an option to view previous year cycles, and to overlay the different year's cycles within each toggle option I mentioned earlier.

I think the website is great already and these few ideas might help improve the user experience!

Edit: Additional ideas: include whether the school is rolling or non-rolling admissions at the top. And then if it is rolling admissions, include information for the average time from interview to decision.

**Comment by RunningMSN** [comment]
Heya, thanks for the suggestions. Writing them here is ok, another way is filling out the form inside the website which sends us an email with them.

1. We can look into this.
2. You should already be able to do this. On any graph with a legend, you can click an item on the legend which will hide or show that category. E.g. hiding interviews, or only showing acceptances, etc. Additionally, you can drag your cursor on most graphs to zoom in.
3. Yes, we can look into this. Another thing is that the data is retained for the past few years under the historic information tab, but I understand that it is a bit limited.
<img width="1294" alt="image" src="https://github.com/RunningMSN/CycleTrack/assets/94721166/ec3e74d6-f23f-4c24-b692-46f2f4019070">

Thanks again!

**Comment by RunningMSN** [comment]
Everything has been implemented other than rolling vs. non-rolling as that information is not easily accessible to us.
