### ISSUE TITLE
Improved Accuracy of Post Interview Acceptance Rate

### ISSUE THREAD

**Issue by John-D-Boom** [RunningMSN/CycleTrack#5]
Hi,

I've noticed that the post-interview-acceptance rates for MD/PhD programs has changed dramatically throughout the cycle. I believe this is happening because all applicants who are interviewed are included in the denominator of the calculation until they are accepted, at which point the numbers increase dramatically. This behavior is undesirable because it sets an unrealistically low expectation for the overall acceptance rate while applicants are interviewing.

I think that this calculation should change so that students with no information about acceptance are not included anywhere in the calculation. The simplest method would be to just limit it to data from previous cycles. A more nuanced approach would include the current year only if the confirmed rejection or acceptance has been entered, or April 31st has passed and any lack of info can be assumed to be a rejection.

This problem is most pronounced for the post-interview acceptance rate for MD/PhDs simply because there are so few entries that small changes in the denominator cause a big change in overall percentage. A similar problem occurs for the overall interview rate and ofc for MD as well as MD/PhD. However, the numbers are higher there and consequently less susceptible to this error.

**Comment by RunningMSN** [comment]
Hi John, sorry for the long delay, somehow this slipped our attention. I agree this should be changed to include all people who we have a final admissions decision on, and will fix it. Thanks for writing this!
